runs:
  using: "composite"
  steps:
    - name: setup user and permissions
      run: |
        git config --add safe.directory '*'
        adduser --quiet --comment forgejo --disabled-password forgejo
        chown -R forgejo:forgejo .
    - uses: https://codeberg.org/fnetx/setup-cache-go@b2214eaf6fb44c7e8512c0f462a2c3ec31f86a73
      with:
        username: forgejo
